const data = {
    products: [
        {   
            id: 1,
            name: 'ADIDAS SHORT',
            category: 'shorts',
            sex: 'male',
            brand: 'Adidas',
            price: 23,
            description:'High quality product',
            rating: 1,
            numReviews: 12,
            stock: 14,
            size: 'Medium',
            image: '/imagee/adidas-short1.jpg'
        },
        {   
            id: 2,
            name: 'ADIDAS SLIM SHIRT',
            category: 'shirts',
            sex: 'male',
            brand: 'Adidas',
            price: 99,
            description:'High quality product',
            rating: 1.5,
            numReviews: 23,
            stock: 30,
            size: 'Large',
            image: '/imagee/adidas-slim-shirt.jpg'
        },
        {   
            id: 3,
            name: 'LACOSTE SHIRT',
            category: 'shirts',
            sex: 'male',
            brand: 'Lacoste',
            price: 58,
            description:'High quality product',
            rating: 2,
            numReviews: 33,
            stock: 10,
            size: 'Small',
            image: '/imagee/lacoste-shirt.jpg'
        },
        {   
            id: 4,
            name: 'H&M PANTS',
            category: 'pants',
            sex: 'female',
            brand: 'H&M',
            price: 120,
            description:'High quality product',
            rating: 2.5,
            numReviews: 20,
            stock: 3,
            size: 'Medium',
            image: '/imagee/hm-pants.jpg'
        },
        {   
            id: 5,
            name: 'JACK&JONES SHOES',
            category: 'shoes',
            sex: 'male',
            brand: 'Jack&Jones',
            price: 180,
            description:'High quality product',
            rating: 3,
            numReviews: 27,
            stock: 10,
            size: '33',
            image: '/imagee/jack-shoes.jpg'
        },
        {   
            id: 6,
            name: 'SLIM PANTS',
            category: 'pants',
            sex: 'female',
            brand: 'H&M',
            price: 120,
            description:'High quality product',
            rating: 3.5,
            numReviews: 20,
            stock: 3,
            size: 'Medium',
            image: '/imagee/hm-pants1.jpg'
        },
        {   
            id: 7,
            name: 'POLO SHIRT',
            category: 'shirt',
            sex: 'female',
            brand: 'lacoste',
            price: 87,
            description:'High quality product',
            rating: 4,
            numReviews: 20,
            stock: 3,
            size: 'Medium',
            image: '/imagee/lacoste-shirt1.jpg'
        },
        {   
            id: 8,
            name: 'SLIM SHIRT',
            category: 'shirt',
            sex: 'female',
            brand: 'jack&jones',
            price: 60,
            description:'High quality product',
            rating: 4.5,
            numReviews: 29,
            stock: 15,
            size: 'Medium',
            image: '/imagee/jack-shirt.jpg'
        },
        {   
            id: 9,
            name: 'ADIDAS SHOES',
            category: 'shoes',
            sex: 'female',
            brand: 'adidas',
            price: 213,
            description:'High quality product',
            rating: 5,
            numReviews: 43,
            stock: 33,
            size: 'Medium',
            image: '/imagee/adidas-shoe.jpg'
        },
    ]
}

export default data